// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;

/*
 * This class does an email login authentication check using
 * the email mumsrecipeuser@hotmail.com in Chrome Browser.
 */
public class EmailLoginAuthenticationTest1 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    // Chrome Browser setup.
    System.setProperty("webdriver.chrome.driver", "driver/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void emailLoginAuthenticationTest1() {
    driver.get("http://localhost:5000");
    driver.manage().window().maximize();
    // Locate and click the email option.
    driver.findElement(By.cssSelector(".firebaseui-idp-password > .firebaseui-idp-text-long")).click();
    // 5 seconds timeout required for google login interface to load
    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
    driver.findElement(By.name("email")).click();
    // Enter email as "mumsrecipeuser@hotmail.com"
    driver.findElement(By.name("email")).sendKeys("mumsrecipeuser@hotmail.com");
    driver.findElement(By.cssSelector(".firebaseui-id-submit")).click();
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("P@ssw0rd1");
    driver.findElement(By.cssSelector(".firebaseui-id-submit")).click();

    int totalTimeWaited = 1;
    boolean isLoginSuccessful = true;
    try {
      // Keep checking if login is successful or not.
      while (!driver.getTitle().equals("Mum's Recipes")) {
        Thread.sleep(1000);
        totalTimeWaited++; // Each increment is equivalent to 1 second.

        if (totalTimeWaited >= 10) { // total amount of time spent waiting >= 10 seconds
          System.out.println("EmailLoginAuthenticationTest1: FAIL. Incorrect login!");
          isLoginSuccessful = false;
        }
      }
    } catch (Exception e) {
      System.out.println(""+ e.toString());
    }

    assertTrue(isLoginSuccessful);
  }
}
